\doxysection{exceptions.\+Duplicate\+Customer\+Error Class Reference}
\hypertarget{classexceptions_1_1DuplicateCustomerError}{}\label{classexceptions_1_1DuplicateCustomerError}\index{exceptions.DuplicateCustomerError@{exceptions.DuplicateCustomerError}}


Inheritance diagram for exceptions.\+Duplicate\+Customer\+Error\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=247pt]{classexceptions_1_1DuplicateCustomerError__inherit__graph}
\end{center}
\end{figure}


Collaboration diagram for exceptions.\+Duplicate\+Customer\+Error\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=247pt]{classexceptions_1_1DuplicateCustomerError__coll__graph}
\end{center}
\end{figure}
\doxysubsubsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
\Hypertarget{classexceptions_1_1DuplicateCustomerError_aa7532e958ca869e10bd70149eb515e7f}\label{classexceptions_1_1DuplicateCustomerError_aa7532e958ca869e10bd70149eb515e7f} 
{\bfseries \+\_\+\+\_\+init\+\_\+\+\_\+} (self, int user\+\_\+id)
\end{DoxyCompactItemize}


\doxysubsection{Detailed Description}
\begin{DoxyVerb}Raised when a customer with the same user_id already exists.\end{DoxyVerb}
 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
app/exceptions.\+py\end{DoxyCompactItemize}
